
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.*;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nitin
 */
public class ParticipantJFrame extends javax.swing.JFrame {
int res;
    /**
     * Creates new form ParticipantJFrame
     */
    public ParticipantJFrame() {
        initComponents();
    }

    ParticipantJFrame(int counting) {
        res=counting;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        com = new com.toedter.components.JLocaleChooser();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ph = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ma = new javax.swing.JRadioButton();
        fe = new javax.swing.JRadioButton();
        ot = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        occ = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        da = new com.toedter.calendar.JDateChooser();
        submitbut = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        emp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 85)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registration Form");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 820, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\JAVA DBMS Project\\A New Design - Made with PosterMyWall (6).png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 150));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\JAVA DBMS Project\\A New Design - Made with PosterMyWall (6).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 460, 150));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\JAVA DBMS Project\\A New Design - Made with PosterMyWall (6).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 280, 150));

        jPanel2.setBackground(new java.awt.Color(247, 247, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        com.setBackground(new java.awt.Color(204, 204, 255));
        com.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comActionPerformed(evt);
            }
        });
        jPanel2.add(com, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 260, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, 40));

        name.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 380, 40));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel6.setText("E-Mail ID :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 40));

        mail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 380, 40));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" Language :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 210, 70));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel8.setText("Mobile No : ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        ph.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phKeyTyped(evt);
            }
        });
        jPanel2.add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 380, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("+91");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 60, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel10.setText("Gender :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        ma.setBackground(new java.awt.Color(204, 204, 255));
        ma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ma.setText(" Male");
        ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maActionPerformed(evt);
            }
        });
        jPanel2.add(ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 80, 40));

        fe.setBackground(new java.awt.Color(204, 204, 255));
        fe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fe.setText(" Female");
        fe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feActionPerformed(evt);
            }
        });
        jPanel2.add(fe, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 100, 40));

        ot.setBackground(new java.awt.Color(204, 204, 255));
        ot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ot.setText(" Other");
        ot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otActionPerformed(evt);
            }
        });
        jPanel2.add(ot, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 90, 40));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel11.setText(" Occupation :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 250, -1));

        occ.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        occ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher", "Other" }));
        occ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occActionPerformed(evt);
            }
        });
        jPanel2.add(occ, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 260, 120, 30));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel12.setText("DOB :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, -1));

        da.setDateFormatString("dd-MM-yyyy");
        da.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, 180, 30));

        submitbut.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        submitbut.setText("Submit");
        submitbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbutActionPerformed(evt);
            }
        });
        jPanel2.add(submitbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 150, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 150, 60));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 150, 60));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel13.setText("Address :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 150, 50));

        ad.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        jPanel2.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, 300, 40));

        emp.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        emp.setForeground(new java.awt.Color(255, 0, 0));
        emp.setText("Field(s) are empty");
        jPanel2.add(emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 340, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1210, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
     public void close1()
    {
        WindowEvent closeWindow= new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
     
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        
      
        
    }//GEN-LAST:event_nameActionPerformed

    private void maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maActionPerformed
        // TODO add your handling code here:
        
        if(ma.isSelected())
        {
            fe.setSelected(false);
            ot.setSelected(false);
        }
    }//GEN-LAST:event_maActionPerformed

    private void feActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feActionPerformed
        // TODO add your handling code here:
         if(fe.isSelected())
        {
            ma.setSelected(false);
            ot.setSelected(false);
        }
    }//GEN-LAST:event_feActionPerformed

    private void otActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otActionPerformed
        // TODO add your handling code here:
         if(ot.isSelected())
        {
            fe.setSelected(false);
            ma.setSelected(false);
        }
    }//GEN-LAST:event_otActionPerformed

    private void phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_phKeyTyped

    private void submitbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbutActionPerformed
        // TODO add your handling code here:
        
     
     
     
     
        if(name.getText().trim().isEmpty()&& mail.getText().trim().isEmpty()&& ph.getText().trim().isEmpty()&& ad.getText().trim().isEmpty() &&ma.isSelected()==false && fe.isSelected()==false && ot.isSelected()==false && ((JTextField)da.getDateEditor().getUiComponent()).getText().isEmpty())
        {
         emp.setText("Field(s) are empty");
        }
        else if(name.getText().trim().isEmpty())
        {
            emp.setText("Name Field is empty");
        }
        else if(mail.getText().trim().isEmpty())
        {
            emp.setText("E-mail Field is empty");
        }
        else if(ph.getText().trim().isEmpty())
        {
            emp.setText("Phone Number Field is empty");
        }
        else if(ma.isSelected()==false && fe.isSelected()==false && ot.isSelected()==false)
           {
               emp.setText("Make a selection in gender field");
           }
        else if(((JTextField)da.getDateEditor().getUiComponent()).getText().isEmpty())
        {
            emp.setText("Date Of Birth Field is Empty");
        }
           else if(ad.getText().trim().isEmpty())
        {
            emp.setText("Address Field is empty");
        }
           
      
        else{
              
               
               
         
         
        
            try {
                
                
                 String names1=name.getText();
         String mails=mail.getText();
         String phs=ph.getText();
         
             
         
         Locale comms=com.getLocale();
         String dates=((JTextField)da.getDateEditor().getUiComponent()).getText();
         String occs=(String) occ.getSelectedItem();         
         String adds=ad.getText();
                
                
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/regform","root","");
          PreparedStatement ps=con.prepareStatement("insert into rform(names,mailid,mobileno,gender,language,dateofbirth,occupation,address)values(?,?,?,?,?,?,?,?)");
          ps.setString(1, names1);
          ps.setString(2, mails);
          ps.setString(3, phs);
          if(ma.isSelected())
          {
          ps.setString(4, ma.getText());
          }
          else if(fe.isSelected())
          {
          ps.setString(4, fe.getText());
          }
          else if(ot.isSelected())
          {
          ps.setString(4, ot.getText());
          }
          ps.setString(5, comms.toString());
          ps.setString(6, dates);
          ps.setString(7, occs);
          ps.setString(8, adds);
          
          
          ps.executeUpdate();
          JOptionPane.showMessageDialog(null,"Successfully registered!");
          con.close();
                
                
            } catch (Exception ex) {
                System.out.print(ex);
            }
         
         
         
         
         
        close1();
        RulesJFrame rj= new RulesJFrame();
        rj.setVisible(true);
        }
    }//GEN-LAST:event_submitbutActionPerformed

    public void resetting(){
        name.setText(null);
        mail.setText(null);
        ph.setText(null);
        com.setSelectedIndex(105);
        occ.setSelectedIndex(0);
        da.setDate(null);
        ma.setSelected(false);
        fe.setSelected(false);
        ot.setSelected(false);
        ad.setText(null);
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        resetting();
    }//GEN-LAST:event_jButton2ActionPerformed

     public void close()
    {
        WindowEvent closeWindow= new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to EXIT?","Confirmation", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comActionPerformed

    private void occActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_occActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParticipantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParticipantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParticipantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParticipantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParticipantJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private com.toedter.components.JLocaleChooser com;
    private com.toedter.calendar.JDateChooser da;
    private javax.swing.JLabel emp;
    private javax.swing.JRadioButton fe;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton ma;
    private javax.swing.JTextField mail;
    public static javax.swing.JTextField name;
    private javax.swing.JComboBox<String> occ;
    private javax.swing.JRadioButton ot;
    private javax.swing.JTextField ph;
    private javax.swing.JButton submitbut;
    // End of variables declaration//GEN-END:variables
}
